"""
Supabase 간단 연결 테스트 (Python Client만 사용)
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()


def main():
    print("\n" + "🚀"*30)
    print("Seoul Location Services - Supabase 연결 테스트 (Simple)")
    print("🚀"*30 + "\n")

    # Load credentials
    url = os.getenv('SUPABASE_URL')
    key = os.getenv('SUPABASE_KEY')

    if not url or not key:
        print("❌ 환경변수가 설정되지 않았습니다!")
        print(f"   SUPABASE_URL: {url}")
        print(f"   SUPABASE_KEY: {'설정됨' if key else '없음'}")
        sys.exit(1)

    print(f"📍 Supabase URL: {url}")
    print(f"🔑 API Key: {key[:30]}...\n")

    try:
        # Create client
        supabase: Client = create_client(url, key)
        print("✅ 1. Supabase 클라이언트 생성 성공!\n")

        # Test tables
        print("="*60)
        print("테이블 접근 테스트")
        print("="*60)

        tables = [
            'cultural_events',
            'libraries',
            'cultural_spaces',
            'public_reservations',
            'future_heritages',
            'collection_logs'
        ]

        all_success = True

        for table in tables:
            try:
                result = supabase.table(table).select('*', count='exact').limit(1).execute()
                count = result.count if result.count is not None else 0
                print(f"✅ {table:<30} (레코드: {count}개)")
            except Exception as e:
                print(f"❌ {table:<30} (오류: {str(e)[:50]}...)")
                all_success = False

        # Summary
        print("\n" + "="*60)
        if all_success:
            print("🎉 모든 테이블 접근 성공!")
            print("\n다음 단계:")
            print("1. Supabase SQL Editor에서 init_supabase_schema.sql 실행")
            print("2. 데이터 수집 스크립트 작성 (Day 3-5)")
            print("\n테이블이 비어있는 것은 정상입니다.")
            print("데이터 수집 스크립트를 실행하면 데이터가 채워집니다.")
        else:
            print("⚠️  일부 테이블 접근 실패")
            print("\n해결 방법:")
            print("1. Supabase Dashboard → SQL Editor 접속")
            print("2. backend/scripts/init_supabase_schema.sql 파일 내용 복사")
            print("3. SQL Editor에 붙여넣고 'Run' 클릭")

        print("="*60 + "\n")

        # Test insert/update/delete
        print("="*60)
        print("CRUD 작업 테스트")
        print("="*60)

        try:
            # Insert test record
            print("\n📝 테스트 레코드 삽입...")
            insert_result = supabase.table('cultural_events').insert({
                'api_id': 'test_crud_001',
                'title': '테스트 문화행사',
                'lat': 37.5665,
                'lot': 126.9780
            }).execute()

            if insert_result.data:
                test_id = insert_result.data[0]['id']
                print(f"✅ 삽입 성공! (ID: {test_id})")

                # Select
                print("\n🔍 레코드 조회...")
                select_result = supabase.table('cultural_events')\
                    .select('*')\
                    .eq('id', test_id)\
                    .execute()

                if select_result.data:
                    print(f"✅ 조회 성공! (제목: {select_result.data[0]['title']})")

                    # Check if location was auto-generated by trigger
                    has_location = select_result.data[0].get('location') is not None
                    if has_location:
                        print("✅ Trigger 동작 확인! location 필드 자동 생성됨")
                    else:
                        print("⚠️  Trigger 미동작: location 필드가 없습니다")

                # Update
                print("\n✏️  레코드 업데이트...")
                update_result = supabase.table('cultural_events')\
                    .update({'title': '테스트 문화행사 (수정됨)'})\
                    .eq('id', test_id)\
                    .execute()

                if update_result.data:
                    print(f"✅ 업데이트 성공!")

                # Delete
                print("\n🗑️  테스트 레코드 삭제...")
                delete_result = supabase.table('cultural_events')\
                    .delete()\
                    .eq('id', test_id)\
                    .execute()

                print("✅ 삭제 성공!")

                print("\n🎉 모든 CRUD 작업 성공!")

        except Exception as e:
            print(f"\n❌ CRUD 테스트 실패: {str(e)}")

        print("="*60 + "\n")

        # Final summary
        print("="*60)
        print("🎯 최종 결과")
        print("="*60)
        print("✅ Supabase 연결: 성공")
        print("✅ 기본 기능: 정상 동작")
        print("\n📌 현재 상태:")
        print("- Supabase Python Client 연결 완료")
        print("- 테이블 스키마 생성 완료")
        print("- CRUD 작업 가능")
        print("\n⚠️  주의사항:")
        print("- PostgreSQL 직접 연결은 선택사항입니다")
        print("- Python Client만으로도 모든 작업 가능")
        print("- 데이터 수집부터는 Python Client 사용")
        print("="*60 + "\n")

        print("🚀 준비 완료! Day 2 작업을 계속 진행하세요.\n")

    except Exception as e:
        print(f"\n❌ 오류 발생: {type(e).__name__}")
        print(f"   메시지: {str(e)}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
